### ISSUE TITLE
CCIC生产环境ERROR日志摘要-20161209-1

### ISSUE THREAD

**Issue by ebaocloud-ops-cn** [ebaocloud-ops-cn/error-monitor#1]
**Time@IP**
2016-12-08 18:49:34.591  @10.139.108.115 

**File**
RestException.java:62

**Message**
```接口交互失败。
com.ebao.insurance.common.exception.GenericException: 接口交互失败。
	at com.ebao.insurance.ccic.rest.ChannelPaymentResources.forwardPayment(ChannelPaymentResources.java:66) ~[ccic-insurance-1.2.2-SNAPSHOT.jar:na]
	at sun.reflect.GeneratedMethodAccessor1426.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_79]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_79]
	at org.jboss.restea

	at com.ebao.insurance.common.security.defence.filter.DefenceFilter.doFilterInternal(DefenceFilter.java:30) [foundation-1.2.2-SNAPSHOT.jar:na]

	at com.ebao.insurance.common.security.LocalFilterSecurityInterceptor.invoke(LocalFilterSecurityInterceptor.java:54) [foundation-1.2.2-SNAPSHOT.jar:na]

	at com.ebao.insurance.common.security.LocalFilterSecurityInterceptor.doFilter(LocalFilterSecurityInterceptor.java:41) [foundation-1.2.2-SNAPSHOT.jar:na]

	at com.ebao.insurance.tenant.TenantSecurityFilter.doFilterInternal(TenantSecurityFilter.java:32) [foundation-1.2.2-SNAPSHOT.jar:na]

	at com.ebao.insurance.tenant.TenantHolderFilter.doFilterInternal(TenantHolderFilter.java:36) [foundation-1.2.2-SNAPSHOT.jar:na]

	at com.ebao.insurance.common.localization.ParameterValidateFilter.doFilterInternal(ParameterValidateFilter.java:59) [foundation-1.2.2-SNAPSHOT.jar:na]

	at com.ebao.insurance.common.localization.MyRequestContextFilter.doFilterInternal(MyRequestContextFilter.java:72) [foundation-1.2.2-SNAPSHOT.jar:na]```

**Comment by ebaocloud-ops-cn** [comment]
update
