### ISSUE TITLE
Zking生产ERROR摘要 2016-12-16 09:00:02

### ISSUE THREAD

**Issue by ebaocloud-ops-cn** [ebaocloud-ops-cn/error-monitor#30]
* 2016-12-15 21:24:27.629  @10.253.0.60 
 **ZKingBasePolicyAfterPayDataExporter.java:58** 
 zking error:
org.apache.axis2.AxisFault: Connection refused
	at org.apache.axis2.AxisFault.makeFault(AxisFault.java:430) ~[axis2-kernel-1.6.1.jar:1.6.1]
	at org.apache.axis2.transport.http.HTTPSender.sendViaPost(HTTPSender.java:197) ~[axis2-transport-http-1.6.1.jar:na]
	at org.apache.axis2.transport.http.HTTPSender.send(HTTPSender.java:75) ~[axis2-transport-http-1.6.1.jar:na]
	at org.apache.axis2.transport.http.CommonsHTTPTransportSender.writeMessageWithCommons(CommonsHTTPTransportSender.java:404) ~[axis2-transport-http-1.6.1.jar:na]
	at org.apache.axis2.transport.http.CommonsHTTPTransportSender.invoke(CommonsHTTPTransportSender.java:231) ~[axis2-transport-http-1.6.1.jar:na]
	at org.apache.axis2.engine.AxisEngine.send(AxisEngine.java:443) ~[axis2-kernel-1.6.1.jar:1.6.1]
	at org.apache.axis2.description.OutInAxisOperationClient.send(OutInAxisOperation.java:406) ~[axis2-kernel-1.6.1.jar:1.6.1]
	at org.apache.axis2.description.OutInAxisOperationClient.executeImpl(OutInAxisOperation.java:229) ~[axis2-kernel-1.6.1

	at com.ebao.insurance.common.utils.http.SpSoapClientUtils.soapAxis2Connect(SpSoapClientUtils.java:137) ~[foundation-1.2.2-SNAPSHOT.jar:na]

	at com.ebao.insurance.common.utils.http.SpSoapClientUtils$1.doWithRetry(SpSoapClientUtils.java:112) ~[foundation-1.2.2-SNAPSHOT.jar:na]

	at com.ebao.insurance.common.utils.http.SpSoapClientUtils.retrySoapAxis2Connect(SpSoapClientUtils.java:108) ~[foundation-1.2.2-SNAPSHOT.jar:na]

	at com.ebao.insurance.zking.exp.ZKingBasePolicyAfterPayDataExporter.export(ZKingBasePolicyAfterPayDataExporter.java:44) ~[zking-insurance-1.2.2-SNAPSHOT.jar:na]

	at com.ebao.insurance.zking.exp.life.ZKingLifePolicyAfterPayDataExporter.export(ZKingLifePolicyAfterPayDataExporter.java:26) [zking-insurance-1.2.2-SNAPSHOT.jar:na]

	at com.ebao.insurance.exp.PolicyDataExporterImpl.doExport(PolicyDataExporterImpl.java:44) [integration-insurers-1.2.2-SNAPSHOT.jar:na]

	at com.ebao.insurance.policy.workflow.task.ExportPolicyAfterPayTask.execute(ExportPolicyAfterPayTask.java:35) [policyadmin-service-1.2.2-SNAPSHOT.jar:na]

	at com.ebao.insurance.policy.workflow.TaskBundle.execute(TaskBundle.java:42) [policyadmin-service-1.2.2-SNAPSHOT.jar:na]

	at com.ebao.insurance.pa.service.impl.PolicyServiceImpl.issuePolicyAfterPay(PolicyServiceImpl.java:50) [policyadmin-service-1.2.2-SNAPSHOT.jar:na]

	at com.ebao.insurance.zking.rest.ZKingWechatPaymentResources.paymentCallback_aroundBody2(ZKingWechatPaymentResources.java:139) [zking-insurance-1.2.2-SNAPSHOT.jar:na]

	at com.ebao.insurance.zking.rest.ZKingWechatPaymentResources$AjcClosure3.run(ZKingWechatPaymentResources.java:1) [zking-insurance-1.2.2-SNAPSHOT.jar:na]

	at com.ebao.insurance.zking.rest.ZKingWechatPaymentResources.paymentCallback(ZKingWechatPaymentResources.java:99) [zking-insurance-1.2.2-SNAPSHOT.jar:na]

	at com.ebao.insurance.common.security.defence.filter.DefenceFilter.doFilterInternal(DefenceFilter.java:30) [foundation-1.2.2-SNAPSHOT.jar:na]

	at com.ebao.insurance.common.security.LocalFilterSecurityInterceptor.invoke(LocalFilterSecurityInterceptor.java:54) [foundation-1.2.2-SNAPSHOT.jar:na]

	at com.ebao.insurance.common.security.LocalFilterSecurityInterceptor.doFilter(LocalFilterSecurityInterceptor.java:41) [foundation-1.2.2-SNAPSHOT.jar:na]

	at com.ebao.insurance.tenant.TenantSecurityFilter.doFilterInternal(TenantSecurityFilter.java:32) [foundation-1.2.2-SNAPSHOT.jar:na]

	at com.ebao.insurance.tenant.TenantHolderFilter.doFilterInternal(TenantHolderFilter.java:36) [foundation-1.2.2-SNAPSHOT.jar:na]

	at com.ebao.insurance.common.localization.ParameterValidateFilter.doFilterInternal(ParameterValidateFilter.java:59) [foundation-1.2.2-SNAPSHOT.jar:na]

	at com.ebao.insurance.common.localization.MyRequestContextFilter.doFilterInternal(MyRequestContextFilter.java:72) [foundation-1.2.2-SNAPSHOT.jar:na]

------------------------>>> Caused by: java.net.ConnectException: Connection refused 

* 2016-12-15 21:24:27.630  @10.253.0.60 
 **ZKingBasePolicyAfterPayDataExporter.java:59** 
 <?xml version="1.0" encoding="UTF-8"?>
    <Packet type="REQUEST" version="1.0">
        <Head>
            <TransType>J0101</TransType>
                        <TransID>PZKWXB2CPA161200000116</TransID>
            <TransDate>2016-12-15 21:09:27</TransDate>
            <RequestType>02</RequestType>
            <User>YBY_PROD</User>
            <Password>fnkal58202</Password>
        </Head>
        <Body>
            <BasePart>
                <ProposalNo></ProposalNo>
                <OrderNo>PZKWXB2CPA161200000116</OrderNo>
                <BusinessNature>8</BusinessNature>
                <BusinessType>02</BusinessType>
                <Category>PA_PLAN</Category>
                <SumAmount>1800000</SumAmount>
                <SumPremium>3</SumPremium>
                <SumQuantity>1</SumQuantity>
                <RiskCode>0798</RiskCode>
                <GoalInsuredFlag>0</GoalInsuredFlag>
                <AutoTransRenewFlag>99</AutoTransRenewFlag>
                <ShareHolderFlag>0</ShareHolderFlag>

**Comment by ebaocloud-ops-cn** [comment]
@guangmeng-zhai-ebao test email
